version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - 8001:5000
    volumes:
      - .:/app/
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306
